filebeat.inputs:
  - type: filestream
    id: logs
    fields_under_root: true
    encoding: utf-8
    fields:
      event.dataset: logs
    paths:
      - /var/log/logs/*.log

setup.kibana:
  host: 'kibana:5601'
output.logstash:
  hosts: 'logstash:6001'
