version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: simon
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: blogs_api
    ports:
      - '5432:5432'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - '6000:6000'
      - '6001:6001'
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - '5601:5601'
    networks:
      - elk

  filebeat:
    build:
      context: filebeat/
    environment:
      - strict.perms=false
    container_name: filebeat
    volumes:
      - ./logs:/var/log/logs:ro
    depends_on:
      - logstash
    networks:
      - elk

networks:
  elk:
    driver: bridge
