name: Linting

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Lint Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # The linter won't run on submodules
        # with:
        #   submodules: recursive
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Run lint-staged
        run: yarn lint-staged --diff="${GITHUB_BASE_REF}...${GITHUB_HEAD_REF}"
        id: lint
