name: Linting

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Lint Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Run lint-staged
        run: yarn lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
        id: lint
