name: Linting

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: yarn test
        id: test
